# Generated by Django 5.2.3 on 2026-03-01 12:00

import decimal
from django.db import migrations, models

MAX_BALANCE_INTEGER_PART = 9999999999


def sanitize_balance_before_decimal(apps, schema_editor):
    CustomUser = apps.get_model("account", "CustomUser")
    for user in CustomUser.objects.all().only("id", "balance"):
        value = user.balance
        if value is None:
            user.balance = 0
            user.save(update_fields=["balance"])
            continue

        try:
            int_value = int(value)
        except (TypeError, ValueError):
            user.balance = 0
            user.save(update_fields=["balance"])
            continue

        if int_value > MAX_BALANCE_INTEGER_PART:
            user.balance = MAX_BALANCE_INTEGER_PART
            user.save(update_fields=["balance"])
        elif int_value < -MAX_BALANCE_INTEGER_PART:
            user.balance = -MAX_BALANCE_INTEGER_PART
            user.save(update_fields=["balance"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_customuser_balance"),
    ]

    operations = [
        migrations.RunPython(sanitize_balance_before_decimal, noop_reverse),
        migrations.AlterField(
            model_name="customuser",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=decimal.Decimal("0.00"),
                max_digits=12,
                null=True,
            ),
        ),
    ]
